name: pokedex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
